#!/usr/bin/env python3
"""Generate stable ID / routing index artifacts for doc_architecture section 5."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

from corpus_paths import CORE_FILES, COMPANION_WRAPPERS  # noqa: E402

try:
    from router_table_lib import load_router_rows
except ImportError:
    load_router_rows = None  # type: ignore[assignment,misc]


def chapter_rows(root: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for rel in CORE_FILES:
        path = root / rel
        if not path.is_file():
            continue
        chapter = rel.split("_", 1)[0].replace("core_", "").replace("-", "–", 1)
        rows.append(
            {
                "file": rel,
                "label": chapter,
                "status": "present",
            }
        )
    for rel in COMPANION_WRAPPERS:
        rows.append({"file": rel, "label": rel.replace(".md", ""), "status": "present"})
    return rows


def router_sample(root: Path, limit: int = 25) -> list[dict[str, str]]:
    if load_router_rows is None:
        return []
    rows = load_router_rows(root)
    sample: list[dict[str, str]] = []
    for row in rows[:limit]:
        sample.append(
            {
                "id": row.row_id,
                "topic": row.topic,
                "primary_owner": row.owner_cell.strip()[:80],
            }
        )
    return sample


def render_markdown(root: Path) -> str:
    chapters = chapter_rows(root)
    router = router_sample(root)
    lines = [
        "# Generated stable ID index",
        "",
        "Auto-generated by `make architecture-index`. Do not edit by hand.",
        "",
        "## Core and companion files",
        "",
        "| File | Label | Status |",
        "|------|-------|--------|",
    ]
    for row in chapters:
        lines.append(f"| `{row['file']}` | {row['label']} | {row['status']} |")
    lines.extend(
        [
            "",
            "## CJS-2.1 router sample",
            "",
            "Full router: [corpus_joint_structure/cjs_02_implementation_integration_map.md](../corpus_joint_structure/cjs_02_implementation_integration_map.md). Audit: `make router-bidirectional-audit`.",
            "",
            "| Stable ID | Topic | Primary owner |",
            "|-----------|-------|---------------|",
        ]
    )
    for row in router:
        lines.append(f"| {row['id']} | {row['topic']} | {row['primary_owner']} |")
    lines.extend(
        [
            "",
            "## Chapter Ten articles",
            "",
            "Article titles and Roman numerals: `make reference-audit` / `core_10-10_rights_part_*.md`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    out_dir = root / "doc_architecture" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)

    md_path = out_dir / "stable_id_index.md"
    json_path = out_dir / "stable_id_index.json"
    payload = {
        "chapters": chapter_rows(root),
        "router_sample": router_sample(root),
    }
    md_path.write_text(render_markdown(root), encoding="utf-8")
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {md_path.relative_to(root)} and {json_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
