#!/usr/bin/env python3
"""Generate a current-file-inventory Mermaid overview for AI navigation.

Does not invent citation counts. Edge weights live in the JSON crossref indexes.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from corpus_paths import COMPANION_WRAPPERS, CORE_FILES


GROUPS = (
    ("Preamble and Chapter One", ("core_00_", "core_01_")),
    ("Definition mechanics (Chapters Two–Four)", ("core_02", "core_04")),
    ("Chapter Five definition stack", ("core_05",)),
    ("Chapter Six Rights Floor", ("core_06",)),
    ("Chapters Seven–Eleven pipelines", ("core_07", "core_08", "core_09", "core_10", "core_11")),
    ("Chapters Twelve–Sixteen", ("core_12", "core_13", "core_16")),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root.")
    parser.add_argument("--output", required=True, help="Output .mmd path.")
    return parser.parse_args()


def node_id(name: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in name)


def files_for_prefixes(prefixes: tuple[str, ...]) -> list[str]:
    return [name for name in CORE_FILES if name.startswith(prefixes)]


def render(root: Path) -> str:
    lines = [
        "%% Generated by tools/generate_dependency_map.py. Do not edit by hand.",
        "%% Citation edges: ai_corpus/indexes/crossref_matrix.json and section_crossref.json.",
        "graph TB",
        '  subgraph Core["Core constitutional files"]',
    ]
    for title, prefixes in GROUPS:
        gid = node_id(title)
        members = files_for_prefixes(prefixes)
        if not members:
            continue
        lines.append(f'    subgraph {gid}["{title}"]')
        for name in members:
            nid = node_id(name)
            lines.append(f'      {nid}["{name}"]')
        lines.append("    end")
    lines.append("  end")
    lines.append('  subgraph Companions["Implementation companions"]')
    for wrapper in COMPANION_WRAPPERS:
        nid = node_id(wrapper)
        folder = wrapper.replace(".md", "/")
        lines.append(f'    {nid}["{wrapper} + {folder}"]')
    lines.append("  end")
    lines.append("  Core --> Companions")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    output = root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(root), encoding="utf-8")
    print(f"Wrote dependency map to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
