#!/usr/bin/env python3
"""Generate a one-file print pack (cover + Preamble + Rights Floor sheet + process chain + one brief).

The pack is process support. It cannot narrow core. Do not edit the generated file by hand.

Usage (from the repo root)::

    python3 tools/generate_print_pack.py --root . --write
    python3 tools/generate_print_pack.py --root . --check
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

from generate_plain_terms_edition import read_edition  # noqa: E402

GENERATED_REL = "doc_architecture/generated/print_pack.md"
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")

PARTS: tuple[tuple[str, str], ...] = (
    ("core_00_preamble.md", "Preamble (binding source)"),
    (
        "doc_architecture/generated/rights_floor_sheet.md",
        "Chapter Six one-liners (generated wall sheet; source articles bind)",
    ),
    (
        "implementation/PROCESS_PIPELINES_READER.md",
        "Process chain (process support; cannot narrow core)",
    ),
    (
        "implementation/adoption/easy_entry/E16_worker_not_owner.md",
        "Sample easy-entry brief (swap for the brief that sounds like your situation)",
    ),
)


def rebase_links(text: str, source_rel: str, dest_rel: str) -> str:
    """Rewrite local markdown links so they resolve from the generated pack."""
    dest_dir = Path(dest_rel).parent
    source_dir = Path(source_rel).parent

    def repl(match: re.Match[str]) -> str:
        label, target = match.group(1), match.group(2)
        stripped = target.strip()
        if stripped.startswith(("http://", "https://", "mailto:", "/")):
            return match.group(0)
        path_part, hash_sep, fragment = stripped.partition("#")
        if not path_part:
            rel = Path(os.path.relpath(source_rel, dest_dir)).as_posix()
            return f"[{label}]({rel}#{fragment})" if fragment else f"[{label}]({rel})"
        resolved = Path(os.path.normpath(str(source_dir / path_part)))
        rel = Path(os.path.relpath(resolved, dest_dir)).as_posix()
        if hash_sep:
            rel = f"{rel}#{fragment}"
        return f"[{label}]({rel})"

    return LINK_RE.sub(repl, text)


def render_pack(root: Path) -> str:
    edition, effective = read_edition(root)
    lines: list[str] = [
        "# Print pack (generated, non-binding)",
        "",
        "Auto-generated by `make print-pack`. Do not edit by hand. Print this file, or print the source files listed below in order.",
        "",
        f"Corpus edition: `{edition}` · effective **{effective}**",
        "",
        "> **Reader guidance (non-operative).** This pack is process support. It is **not** the Constitution. It **cannot narrow** numbered `core_*` files. Opening or printing it is not [Chapter Fifteen §10](../../core_15_amendment_ratification.md#10-ratification-and-adoption) adoption. It does **not** override local, national, or international law ([Chapter Fourteen §5](../../core_14_expansion_supremacy.md#5-relation-to-applicable-external-law)). The wall sheet is one sentence per Article; the numbered Chapter Six files bind. If this pack and a source file disagree, the source file wins.",
        "",
        "Human door: [`implementation/PRINT_PACK.md`](../../implementation/PRINT_PACK.md).",
        "",
        "## Contents",
        "",
    ]
    for rel, title in PARTS:
        lines.append(f"- `{rel}` — {title}")
    lines.extend(
        [
            "",
            "Full Chapter Six source (not inlined here; too long for a first-hour pack): "
            "[part A](../../core_06_rights_part_a.md), "
            "[part B](../../core_06_rights_part_b.md), "
            "[part C](../../core_06_rights_part_c.md), "
            "[part D](../../core_06_rights_part_d.md).",
            "",
        ]
    )
    dest_rel = GENERATED_REL
    for rel, title in PARTS:
        path = root / rel
        body = path.read_text(encoding="utf-8")
        body = rebase_links(body, rel, dest_rel)
        lines.extend(
            [
                "---",
                "",
                f"## Pack part: {title}",
                "",
                f"Source file: `{rel}`",
                "",
                body.rstrip(),
                "",
            ]
        )
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--root", default=".", help="Repository root.")
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="Write generated file (default).")
    mode.add_argument("--check", action="store_true", help="Fail if generated file is stale.")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = Path(args.root).resolve()
    text = render_pack(root)
    path = root / GENERATED_REL
    if args.check:
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            print("print-pack artifact is stale; run `make print-pack`")
            return 1
        print("print-pack artifact is current.")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"Wrote {GENERATED_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
