#!/usr/bin/env python3
"""Generate a GitHub Pages index of numbered core_* files as repo blob links.

Pages does not republish core. This page lets a Pages visitor open the files
where GitHub already renders them. Do not edit the generated file by hand.

Usage (from the repo root)::

    python3 tools/generate_pages_corpus_index.py --root . --write
    python3 tools/generate_pages_corpus_index.py --root . --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

from corpus_paths import CORE_FILES  # noqa: E402
from generate_plain_terms_edition import read_edition  # noqa: E402

OUT_REL = "docs/corpus_index.md"
BLOB = "https://github.com/kfoelsch/Sentient_Constitution/blob/main/"
HEADING_RE = re.compile(r"^#{1,6}\s+(.*)$")


def first_heading(root: Path, rel: str) -> str:
    for line in (root / rel).read_text(encoding="utf-8").splitlines():
        match = HEADING_RE.match(line.strip())
        if match:
            title = re.sub(r"<[^>]+>", "", match.group(1)).strip()
            return title or rel
    return rel


def render(root: Path) -> str:
    edition, effective = read_edition(root)
    lines = [
        "---",
        "title: Numbered core files (GitHub render)",
        "description: Pointer index. /docs blob fallback. Full render: make pages-site / Pages workflow.",
        "---",
        "",
        "# Numbered core files — open where GitHub renders them",
        "",
        "This page is **process support**. It is **not** the Constitution. Opening it is not adoption.",
        "",
        f"Corpus edition: `{edition}` · effective **{effective}**",
        "",
        "> This `/docs` Pages host does **not** copy numbered `core_*` files. Relative `../core_*` links from `docs/` 404. The links below open the same files in the repository. A **full render** (same files, assembled at build time, not a second constitution) is `make pages-site` and `.github/workflows/pages.yml` — set GitHub Pages source to GitHub Actions. If this page and a `core_*` file disagree, the `core_*` file wins. Canonical public door: [START_HERE.md]("
        + BLOB
        + "START_HERE.md).",
        "",
        "Auto-generated by `make pages-corpus-index`. Do not edit by hand.",
        "",
        "## Binding source",
        "",
    ]
    for rel in CORE_FILES:
        title = first_heading(root, rel)
        lines.append(f"- [{title}]({BLOB}{rel}) — `{rel}`")
    lines.extend(
        [
            "",
            "## First-hour companions (process support)",
            "",
            f"- [START_HERE.md]({BLOB}START_HERE.md)",
            f"- [Rights Floor wall sheet]({BLOB}doc_architecture/generated/rights_floor_sheet.md)",
            f"- [Print pack]({BLOB}implementation/PRINT_PACK.md)",
            f"- [Easy-entry briefs]({BLOB}implementation/adoption/easy_entry/README.md)",
            f"- [Process chain]({BLOB}implementation/PROCESS_PIPELINES_READER.md)",
            f"- [FAQ]({BLOB}implementation/FAQ.md)",
            "",
            "If a relative link 404s on this Pages host, use the GitHub links above.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--root", default=".", help="Repository root.")
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="Write generated file (default).")
    mode.add_argument("--check", action="store_true", help="Fail if generated file is stale.")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = Path(args.root).resolve()
    text = render(root)
    path = root / OUT_REL
    if args.check:
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            print("pages corpus index is stale; run `make pages-corpus-index`")
            return 1
        print("pages corpus index is current.")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
