#!/usr/bin/env python3
"""Generate definition hierarchy index from Chapter Five registry + overrides."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

from ch5_paths import (  # noqa: E402
    CH5_AIM_F,
    CH5_AIM_G,
    CH5_BAND_A,
    CH5_BAND_C,
    CH5_BAND_I,
    CH5_BAND_O,
    CH5_BAND_P,
    CH5_LEG_A,
    CH5_LEG_O,
    CH5_LEG_P,
)

FILE_TETRAD_LEG: dict[str, str] = {
    CH5_BAND_O: "Oversight",
    CH5_BAND_P: "Participation",
    CH5_BAND_A: "Accountability",
    CH5_BAND_C: "Continuity",
    CH5_BAND_I: "Integrative",
    CH5_LEG_O: "Oversight",
    CH5_LEG_P: "Participation",
    CH5_LEG_A: "Accountability",
    CH5_AIM_F: "cross-leg",
    CH5_AIM_G: "cross-leg",
}

DEFAULT_CH00_BY_FILE: dict[str, list[str]] = {
    CH5_BAND_O: ["3.5 Oversight"],
    CH5_BAND_P: ["3.4 Participation"],
    CH5_BAND_A: ["3.6 Accountability", "3.7 Timeliness"],
    CH5_BAND_C: ["3.3 Continuity"],
    CH5_BAND_I: ["3.6 Accountability"],
    CH5_LEG_O: ["3.5 Oversight"],
    CH5_LEG_P: ["3.4 Participation"],
    CH5_LEG_A: ["3.6 Accountability", "3.7 Timeliness"],
    CH5_AIM_F: ["3.2 Flourishing"],
    CH5_AIM_G: ["3.3 Continuity"],
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--root", default=".", help="Repository root.")
    p.add_argument(
        "--registry",
        default="ai_corpus/indexes/definition_registry.json",
        help="Definition registry JSON path.",
    )
    p.add_argument(
        "--overrides",
        default="tools/architecture/hierarchy_overrides.json",
        help="Hierarchy override seed path.",
    )
    p.add_argument(
        "--json-out",
        default="doc_architecture/generated/definition_hierarchy.json",
        help="Output JSON path.",
    )
    p.add_argument(
        "--md-out",
        default="doc_architecture/generated/definition_hierarchy.md",
        help="Output Markdown path.",
    )
    return p.parse_args()


def ensure_registry(root: Path, registry_path: Path) -> None:
    if registry_path.is_file():
        return
    subprocess.run(
        [
            sys.executable,
            str(_TOOLS / "generate_definition_registry.py"),
            "--root",
            str(root),
            "--output",
            str(registry_path),
        ],
        check=True,
    )


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def cluster_tags(cluster_name: str, clusters: dict) -> dict:
    for key, value in clusters.items():
        if key in cluster_name or cluster_name in key:
            return dict(value)
    return {}


def default_aim_role(category: str) -> str:
    if category == "dependent_cluster":
        return "cluster_member"
    if category == "independent":
        return "independent"
    return "cluster_member"


def build_entry(defn: dict, overrides: dict) -> dict:
    term = defn["term"]
    source_file = defn["source_file"]
    term_override = overrides.get("terms", {}).get(term, {})
    cluster_name = None
    cluster_tags_data: dict = {}
    if defn.get("cluster_membership"):
        cluster_name = defn["cluster_membership"]["cluster"]
        cluster_tags_data = cluster_tags(cluster_name, overrides.get("clusters", {}))

    tetrad_leg = term_override.get(
        "tetrad_leg",
        cluster_tags_data.get("tetrad_leg", FILE_TETRAD_LEG.get(source_file, "cross-leg")),
    )
    primary_aim = term_override.get(
        "primary_aim",
        cluster_tags_data.get("primary_aim", "cross-cutting"),
    )
    aim_role = term_override.get(
        "aim_role",
        default_aim_role(defn.get("category", "semi_independent")),
    )
    ch00 = term_override.get(
        "ch00_measurement",
        cluster_tags_data.get(
            "ch00_measurement",
            DEFAULT_CH00_BY_FILE.get(source_file, []),
        ),
    )
    if isinstance(ch00, str):
        ch00 = [ch00]

    return {
        "term": term,
        "canonical_file": term_override.get("canonical_file", source_file),
        "anchor": defn["anchor"],
        "line_start": defn["line_start"],
        "definition_class": defn["category"],
        "tetrad_leg": tetrad_leg,
        "primary_aim": primary_aim,
        "aim_role": aim_role,
        "ch00_measurement": ch00,
        "cluster_id": cluster_name,
        "notes": term_override.get("notes", ""),
    }


def render_markdown(payload: dict) -> str:
    lines = [
        "# Generated definition hierarchy index",
        "",
        "Auto-generated by `make hierarchy-map`. Do not edit by hand.",
        "",
        f"Generated: {payload['generated_at']}",
        "",
        f"Entry count: {payload['entry_count']}",
        "",
        "CH5-HIER-01 tag vocabulary: [doc_architecture.md](../doc_architecture.md) section 4.",
        "",
        "| Term | File | Aim role | Primary aim | Tetrad leg | Ch00 measurement | Cluster |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in payload["entries"]:
        ch00 = " · ".join(row["ch00_measurement"]) if row["ch00_measurement"] else "—"
        cluster = row["cluster_id"] or "—"
        lines.append(
            f"| {row['term']} | `{row['canonical_file']}` | {row['aim_role']} | "
            f"{row['primary_aim']} | {row['tetrad_leg']} | {ch00} | {cluster} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    registry_path = root / args.registry
    ensure_registry(root, registry_path)
    overrides = load_json(root / args.overrides)
    registry = load_json(registry_path)

    ch5_entries = [
        d for d in registry["definitions"] if d["category"] != "principle_layer"
    ]
    entries = [build_entry(defn, overrides) for defn in ch5_entries]
    present = {row["term"] for row in entries}
    # Aim / Tetrad-leg apex heads are letter O/M/A/C file heads, not #### leaves —
    # inject them from hierarchy overrides when absent from the registry.
    for term, meta in overrides.get("terms", {}).items():
        if term in present:
            continue
        if meta.get("aim_role") not in {"aim_head", "tetrad_leg_head"}:
            continue
        canonical = meta.get("canonical_file")
        if not canonical:
            continue
        anchor = {
            "Flourishing": "flourishing-constitutional",
            "Continuity (Constitutional Aim)": "continuity-aim-constitutional",
            "Oversight": "oversight-constitutional",
            "Participation": "participation-constitutional",
            "Accountability": "accountability",
            "Timeliness": "timeliness-constitutional",
        }.get(term, "")
        entries.append(
            {
                "term": term,
                "canonical_file": canonical,
                "anchor": anchor,
                "line_start": 1,
                "definition_class": "apex_head",
                "tetrad_leg": meta.get("tetrad_leg", "cross-leg"),
                "primary_aim": meta.get("primary_aim", "cross-cutting"),
                "aim_role": meta["aim_role"],
                "ch00_measurement": (
                    [meta["ch00_measurement"]]
                    if isinstance(meta.get("ch00_measurement"), str)
                    else list(meta.get("ch00_measurement") or [])
                ),
                "cluster_id": None,
                "notes": meta.get("notes", ""),
            }
        )
    entries.sort(key=lambda row: row["term"].casefold())

    payload = {
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source": str(args.registry),
        "overrides": str(args.overrides),
        "entry_count": len(entries),
        "entries": entries,
    }

    json_out = root / args.json_out
    md_out = root / args.md_out
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    md_out.write_text(render_markdown(payload), encoding="utf-8")
    print(f"Wrote {len(entries)} hierarchy rows to {json_out} and {md_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
